[theme]
base = "dark"
primaryColor = "#10B981"
backgroundColor = "#070B12"
secondaryBackgroundColor = "#0C1220"
textColor = "#F1F5F9"
font = "sans serif"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
